### ISSUE TITLE
Only one Set-Cookie header in response

### ISSUE THREAD

**Issue by azlotnikov** [9seconds/httransform#10]
in `headerset.go` `func (hs *HeaderSet) SetBytes(key []byte, value []byte)`
```go
        if position, ok := hs.index[lowerKey]; ok {
		hs.values[position].Value = value
	} else {
		newHeader := getHeader()
		newHeader.ID = lowerKey
		newHeader.Key = append(newHeader.Key, key...)
		newHeader.Value = append(newHeader.Value, value...)
		hs.values = append(hs.values, newHeader)
		hs.index[lowerKey] = len(hs.values) - 1
	}
```
When lowerKey=`set-cookie` only the last one cookie will remain.

Can be easily checked with curl
```
curl -I -X GET -x http://127.0.0.1:64890 https://mail.ru -k
```
1 cookie in response
```
curl -I -X GET https://mail.ru -k
```
2 cookies in response

**Comment by 9seconds** [comment]
I see :/ I'm doing v2 of this library now and gonna address this issue there. This happens with all headers that could be met twice, btw, not only cookies.

**Comment by 9seconds** [comment]
I've just released. Feel free to check. This issue won't happen there.
