### ISSUE TITLE
Question: is it really to rotate MakeProxyChainExecutor on-the-fly?

### ISSUE THREAD

**Issue by vkudyushev** [9seconds/httransform#11]
I've just tried to build a proxy server with your package and have one question: can I rotate proxies inside server per-request on-the-fly?
Thanks.

**Comment by 9seconds** [comment]
You need to implement your own executor. This is not that complex. I have 1 project based on httransform which does exactly that.

**Comment by vkudyushev** [comment]
Thanks for answer! I'll try. 
But while I've wait for your answer I realized my own proxy server, based on net/http (which is not so fast as fasthttp).
