### ISSUE TITLE
Too small buffer size for response headers

### ISSUE THREAD

**Issue by azlotnikov** [9seconds/httransform#29]
Some sites (instagram for example) send large headers.
So the buffer size `const bufioReaderSize = 1024 * 4` is not enough

<img width="993" alt="screen" src="https://user-images.githubusercontent.com/1560126/168162526-a41bb11f-3595-4470-a9b6-198e81084454.png">

Maybe we can have this option moved into config?

For instagram it was enough to set `const bufioReaderSize = 1024 * 5`

**Comment by 9seconds** [comment]
Yes, this is a good idea. Unfortunately, I'm not able to work on that now but will happily accept a PR :)

**Comment by azlotnikov** [comment]
Actually it's already fixed here:
https://github.com/9seconds/httransform/commit/0b4e180c425d4f6143480c17b94f4a999cc1a29e

I didnt check the master branch ;(

it's only needed to push a new tag. So I'm closing this one.
