### ISSUE TITLE
Send on closed channel panic

### ISSUE THREAD

**Issue by mixadior** [9seconds/httransform#8]
```
runtime.fatalpanic at panic.go:690
runtime.gopanic at panic.go:565
runtime.chansend at chan.go:252
runtime.chansend1 at chan.go:127
github.com/9seconds/httransform/ca.(*CA).Get at ca.go:72
github.com/9seconds/httransform.(*Server).makeHijackHandler.func1 at server.go:96
github.com/valyala/fasthttp.hijackConnHandler at server.go:2150
runtime.goexit at asm_amd64.s:1337
 - Async stack trace
github.com/valyala/fasthttp.(*Server).serveConn at server.go:2110
```

After `srv.Shutdown()` some requests still being processed, but certs channels already closed, i tried to create code, that reproduce problem, but failed. 

1. Create chaining proxy
2. Set it in browser 
3. Actively open https sites
4. Shutdown in separate goroutine server, continuing opening sites in browser
5. Panic

It reproduces well, when you actively use headless browsers and do big requests amount.

**Comment by 9seconds** [comment]
Thanks, I'll try to investigate
